{% set name = "lb-nightly-utils" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lb-nightly-utils-{{ version }}.tar.gz
  sha256: 93b653347cf98489bf0232bd71b152c2982ec590e1b45571b767b46d2208fec7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - lb-nightly-configuration >=0.3,<1.0
    - python >=3.6,<4.0
    - requests >=2.26.0,<3.0.0

test:
  imports:
    - lb
    - lb.nightly.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/lb-nightly-utils/
  summary: Common utilities for LHCb Nightly and Continuous Integration Build System
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maszyman
